name: Virtual Machine Building
on: push
jobs:
    build-and-run:
        name: Build and Run
        runs-on: macos-latest 
        steps:
        - uses: actions/checkout@v1
        - name: build code
          run: make
        - name: Nominal Run
          run: ./main
